# Generated by Django 3.2 on 2021-04-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.CharField(blank=True, choices=[('', 'Choose...'), ('American', 'American'), ('European', 'European'), ('French', 'French'), ('Mexican', 'Mexican'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Middle Eastern', 'Middle Eastern'), ('Latin', 'Latin American')], max_length=50, null=True)),
                ('live_capacity', models.CharField(blank=True, choices=[('', 'Choose...'), ('100', '100'), ('75', '75'), ('50', '50'), ('25', '25'), ('10', '10')], max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, choices=[('', 'Choose...'), ('CA', 'California'), ('NY', 'New York'), ('IL', 'Chicago')], max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
