# Generated by Django 3.2 on 2021-05-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dinner10',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dinner5',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dinner6',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dinner7',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dinner8',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dinner9',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('Available', 'Vacant')], max_length=50, null=True),
        ),
    ]
