# Generated by Django 3.2 on 2021-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210501_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lunch1',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lunch10',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lunch11',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lunch12',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lunch2',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lunch9',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dinner10',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dinner5',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dinner6',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dinner7',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dinner8',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dinner9',
            field=models.CharField(blank=True, choices=[('', ''), ('Available', 'Vacant')], max_length=50, null=True),
        ),
    ]
