# Generated by Django 3.2 on 2021-05-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210501_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
