# Generated by Django 3.2 on 2021-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
