# Generated by Django 3.2 on 2021-04-16 08:28

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
    ]
