# Generated by Django 3.2 on 2021-04-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210416_0137'),
        ('comment', '0006_alter_comment_email'),
    ]

    operations = [
    ]
