# Generated by Django 3.2 on 2021-04-30 22:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
