# Generated by Django 3.2 on 2021-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_alter_comment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest',
            field=models.CharField(blank=True, choices=[('', 'Choose...'), ('2', '2 Guests'), ('3', '3 Guests'), ('4', '4 Guests'), ('5+', '5+ Guests')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
