# Generated by Django 3.2 on 2021-05-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20210502_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='guest',
            field=models.CharField(choices=[('', 'Choose...'), ('1', '1 Guest'), ('2', '2 Guests'), ('3', '3 Guests'), ('4', '4 Guests'), ('5+', '5+ Guests')], max_length=50, null=True),
        ),
    ]
